### ISSUE TITLE
[FEATURE]add type annoatation to the library

### ISSUE THREAD

**Issue by wangxin688** [carlkidcrypto/ezsnmp#138]
**Is your feature request related to a problem? No
Thanks for the great forking version.
Since it's not very clear for return type or params type for basic api and lack of IDE autocompletions.

I‘m not familar with C++ code, but I can make some contributions for python part to improve type hint.

**Comment by carlkidcrypto** [comment]
Hello @wangxin688 . Thanks for submitting this feature request. I would gladly accept a PR for typing on the python side of things. Based on documentation it looks like typing has been around since 3.5 https://docs.python.org/3.8/library/typing.html

If and when you open a PR, I ask that you also include unit test coverage to ensure your new feature works, but also to ensure nothing old is broken.

Thanks 👍

**Comment by carlkidcrypto** [comment]
Done in https://github.com/carlkidcrypto/ezsnmp/pull/139
